### ISSUE TITLE
[The Hiker] Altitude

### ISSUE THREAD

**Issue by viktoria7211** [sw21-tug/Team_28#17]
Backend

**Comment by Markus152** [comment]
Update location is the same as for altitue (#4 [https://github.com/sw21-tug/Team_28/projects/1#card-57580277]), to prevent dublicate code this will be handled in one seperate action. The userinterface provides a function to update the location on the map.
Will be handel in ticket #17 [https://github.com/sw21-tug/Team_28/projects/1#card-59525675].
