### ISSUE TITLE
[The Hiker] Humidity

### ISSUE THREAD

**Issue by fdnuka** [sw21-tug/Team_28#26]
As a user,
I want to be able to check the ambient relative humidity when I click on the 'Humidity' button on the main screen. When I click the button another screen should open which should be split in vertical half. The upper half should contain the icon (dots of water) of the humidity and the text 'Humidity'. Icon goes up and the text stays under the icon. The bottom part shows the humidity of the ambient in percentage. Humidity should be refreshed every time the user opens the feature.

**Comment by Nikolas-S** [comment]
**To check if a humidity sensor is available:**
create a SensorManager and use the getDefaultSensor method with Sensor.TYPE_RELATIVE_HUMIDITY as parameter.
If it returns null, no sensor is available.

`val my_sensor_manager = getSystemService(Context.SENSOR_SERVICE) as SensorManager`
`if (my_sensor_manager.getDefaultSensor(Sensor.TYPE_RELATIVE_HUMIDITY) == null) { // no humidity sensor available }`

**To read the humidity:**
create a SensorManager, use the getDefaultSensor method with Sensor.TYPE_RELATIVE_HUMIDITY as parameter to get the humidity sensor.
Next, use the SensorManager to register a SensorEventListener for the humidity sensor using the registerListener method.

`my_sensor_manager.registerListener(my_sensor_event_listener, my_humidity_sensor, SensorManager.SENSOR_DELAY_NORMAL)`
							
The SensorEventListener needs to implement the onSensorChanged and onAccuracyChanged methods. Whenever a new humidity value is available, onSensorChanged will be called. To read the value, onSensorChanged has a parameter called "event". The updated value can be read from "event.values[0]".

[Using humidity sensor (Java)](https://www.youtube.com/watch?v=7vYqBd22sMg)
Official docs: [Environment sensors](https://developer.android.com/guide/topics/sensors/sensors_environment), [relative humidity sensor](https://developer.android.com/reference/android/hardware/SensorEvent#sensor.type_relative_humidity:), [SensorEventListener](https://developer.android.com/reference/android/hardware/SensorEventListener#onSensorChanged(android.hardware.SensorEvent))
[Example on GitHub (Java)](https://github.com/PacktPublishing/Android-Sensor-Programming-By-Example/blob/master/Chapter%203/WeatherUtility-master/app/src/main/java/com/weatherutility/HumidityActivity.java)
