### ISSUE TITLE
[The Hiker] Speed of moving

### ISSUE THREAD

**Issue by fdnuka** [sw21-tug/Team_28#7]
As a user,
when I click on the 'Speed' button on the main screen it should open another screen which should be split in vertical 30% with 70%. The upper half should contain some sort of icon that represents speed and the text 'Moving speed'. Icon goes up and the text stays under the icon. The bottom part shows the moving speed of the user in km/h. Update the moving speed in real-time.

**Comment by chairete** [comment]
Ways to calculate movement speed:
-getSpeed() method of Location class[1]
	returns meters per second
	Problems: may not work on every device (check with hasSpeed())
-calculate it manually between two Location-Points
	to do: save two last locations and time (all provided with Locations from Location Manager)
	Formula: distance/time_passed (times 3,6 to get km/h instead of m/s)
	Problems:	Location inaccuracy (especially indoor)
-calculate it with the accelerometer
	example of how to calculate it [2]
	Problems: can be highly unaccurate. not recommended

Feature does not need to work indoor. (consulated PO regarding that issue)
So calculating it with two Locationpoints would be the best option.
	
[1] https://developer.android.com/reference/android/location/Location#getSpeed()
[2] https://stackoverflow.com/questions/47097127/android-calculating-velocity-wtih-accelerometer-data
